# 版本根据你的docker版本来的，目前主流应该都是3.几的版本
version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.8.0
    volumes:
      - ${ZOOKEEPER_PATH_1}/data:/data
      - ${ZOOKEEPER_PATH_1}/config:/conf
      - ${ZOOKEEPER_PATH_1}/datalog:/datalog
      - ${ZOOKEEPER_PATH_1}/logs:/logs
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - ${ZOOKEEPER_PORT_1}:2181
    restart: always
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_PORT_1}:${KAFKA_PORT_1}
    volumes:
      - ${KAFKA_PATH_1}/data:/kafka
      - ${KAFKA_PATH_1}/config:/opt/kafka/secrets/
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://${LOCAL_IP}:${KAFKA_PORT_1}
      KAFKA_ADVERTISED_PORT: ${KAFKA_PORT_1}
      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:${KAFKA_PORT_1}
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_PORT: ${KAFKA_PORT_1}
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_SUPER_USERS: User:admin
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true" #设置为true，ACL机制为黑名单机制，只有黑名单中的用户无法访问，默认为false，ACL机制为白名单机制，只有白名单中的用户可以访问
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms16M"
      KAFKA_OPTS: -Djava.security.auth.login.config=/opt/kafka/secrets/server_jaas.conf
    restart: always
 ##  kafdrop 监控kafka的Ui工具
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: always
    ports:
       - "19001:9000"
    environment:
       KAFKA_BROKERCONNECT: "kafka:${KAFKA_PORT_1}"
    ## 如kafka开启了sasl认证后以下 sasl认证链接是必要的，下面的事经过base64加密后的结果
       KAFKA_PROPERTIES: ${KAFDROP_BASE64}
       SERVER_SERVLET_CONTEXTPATH: "/kafdrop/"
    depends_on:
      - zookeeper
      - kafka
    cpus: 1
    mem_limit: 1024m
    container_name: kafdrop
    restart: always
